version: "3.7"
services:
  rabbitmq:
    build: ./docker/messenger
    container_name: xchange-rabbitmq
    restart: unless-stopped
    ports:
    - "5672:5672"
    - "15672:15672"

  influxdb:
    container_name: xchange-influxdb
    restart: unless-stopped
    image: influxdb:1.7.10-alpine
    environment:
    - INFLUXDB_DB=xchange
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
    - INFLUXDB_USER=telegraf
    - INFLUXDB_USER_PASSWORD=secretpassword
    ports:
    - "8086:8086"
    volumes:
    - influxdb-volume:/var/lib/influxdb

  chronograf:
    container_name: xchange-chronograf
    image: chronograf:1.8.4-alpine
    ports:
    - "8888:8888"
    volumes:
    - chronograf-volume:/var/lib/chronograf

  grafana:
    container_name: xchange-grafana
    image: grafana/grafana:7.0.1
    ports:
    - "3000:3000"
    volumes:
    - grafana-volume:/var/lib/grafana

volumes:
  influxdb-volume:
  chronograf-volume:
  rabbitmq-volume:
  grafana-volume:

networks:
  default:
    external:
      name: xchange
